name: Node.js CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [23.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Install OpenSSL 1.1
      run: |
        sudo apt update
        sudo apt install -y wget
        wget http://ports.ubuntu.com/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
        sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm test
      env:
        JWT_SECRET: ${{ secrets.JWT_SECRET || 'test_jwt_secret_for_ci' }}
        JWT_EXPIRE: '30d'
        EMAIL_SERVICE: ${{ secrets.EMAIL_SERVICE || 'test' }}
        EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME || 'test@example.com' }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD || 'testpassword' }}
        EMAIL_FROM: ${{ secrets.EMAIL_FROM || 'test@example.com' }}
        MONGODB_URI: ${{ secrets.MONGODB_URI || 'mongodb+srv://khanzada55455:admin123@cluster0.zmurb.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0' }}
    - name: Check code style
      run: npx eslint . --ext .js
